# Generated by Django 4.0.2 on 2022-02-05 22:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_donor',
            field=models.BooleanField(default=True, verbose_name='donor status'),
        ),
        migrations.CreateModel(
            name='Requesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image_url', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/b/b1/Missing-image-232x150.png')),
                ('sold', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('creationdate', models.DateTimeField(default=datetime.datetime(2021, 9, 29, 1, 50, 16, 283956))),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_donor', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('requestorcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='auctions.category')),
            ],
        ),
    ]
