# Generated by Django 4.0.2 on 2022-02-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_user_is_donor_remove_user_is_requestor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_donor',
            field=models.BooleanField(default=True, verbose_name='Donor Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_requestor',
            field=models.BooleanField(default=False, verbose_name='Requestor Status'),
        ),
    ]
