# Generated by Django 4.0.2 on 2022-02-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_profile_is_donor_alter_profile_is_requestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='Zip Code'),
        ),
    ]
