# Generated by Django 4.0.2 on 2022-02-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_profile_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='confirmed',
            field=models.BooleanField(default=False, null=True, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_donor',
            field=models.BooleanField(default=True, null=True, verbose_name='Donor Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_requestor',
            field=models.BooleanField(default=False, null=True, verbose_name='Requestor Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Zip Code'),
        ),
    ]
