# Generated by Django 4.0.2 on 2022-02-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_name_profile_firstname_remove_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='username'),
        ),
    ]
