# Generated by Django 4.0.2 on 2022-02-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Other', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='requesting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
