# Generated by Django 4.0.2 on 2022-02-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_user_is_donor_user_is_requestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
