# Generated by Django 4.0.2 on 2022-02-06 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_requestorcategory_alter_requesting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='requesting',
            name='requestorcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='auctions.requestorcategory'),
        ),
    ]
